# Lua isn't a supported language; using fake-erlang, as per
# http://thejacklawson.com/2012/09/lua-testing-with-busted-and-travis-ci/
language: erlang

before_install: git submodule update --init --recursive

install: sudo apt-get install linux-headers-3.13.0-37 libpcap-dev

script: make && make check
